In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:

# Displays the first review text
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text Cleaning

 1. Sample 10000 rows
 2. Remove html tags
 3. Remove special characters
 4. Converting every thing to lower case
 5. Removing Stop words
 6. Stemming

In [6]:
# This cell samples 10000 rows randomly from the DataFrame for processing
df = df.sample(10000)

In [8]:
df.shape

(10000, 2)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 23348 to 34531
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [10]:
# 'positive' is replaced with 1 and 'negative' with 0, inplace modifies the original DataFrame

df['sentiment'].replace({'positive': 1, 'negative': 0}, inplace=True)

C:\Users\Acer\AppData\Local\Temp\ipykernel_46984\1369801028.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive': 1, 'negative': 0}, inplace=True)
C:\Users\Acer\AppData\Local\Temp\ipykernel_46984\1369801028.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive': 1, 'negative': 0}, inplace=True)

In [11]:
df.head()

                                                  review  sentiment
23348  A guy, with the unlikely name of Shy Walker, l...          0
16753  This is perhaps the worst movie I have ever se...          0
6040   I came across this movie back in the mid eight...          1
24586  Most movies I can sit through easily, even if ...          0
16135  'Iphigenia' is the great achievement of Michae...          1

In [12]:
# a regular expression to remove HTML tags and tests it on the third review
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

"I came across this movie back in the mid eighties as a teenager and it immediately became one of my favorite holiday and non-holiday films. As you can tell from the other reviews this movie has a very good story line and great actors signed on for it. Stanwyck is great as bride to be that is having second thoughts. Dennis Morgan's acting is strong also. He goes unnoticed in most films but was a very capable actor, check out KITTY FOYLE. In this film he plays the visiting sailor that woos Stanwyck away from her husband to be. This is a Christmas classic. The settings and the story make for a great Christmas romance"

In [13]:
# Defining a function to clean HTML tags from text
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [14]:
# Applying clean_html function to the 'review' column of the DataFrame
df['review'] = df['review'].apply(clean_html)

In [15]:
def convert_lower(text):
    return text.lower()

In [16]:
# applying the convert_lower function to the 'review' column
df['review'] = df['review'].apply(convert_lower)

In [17]:
# defining a function to remove special characters, replacing them with spaces
def remove_special(text):
    x = ''
    for i in text:
        if i.isalnum():
            x = x + i
        else:
            x = x + ' '
    return x

In [18]:
# test the remove_special function with a sample text
remove_special(' th%e @ classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare. forget pretty pictures painted for mainstream audiences, f')

' th e   classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare  forget pretty pictures painted for mainstream audiences  f'

In [19]:
# applying the remove_special function to the 'review' column
df['review'] = df['review'].apply(remove_special)

In [20]:
import nltk

In [21]:
from nltk.corpus import stopwords

In [22]:
# display the list of English stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [23]:
df

                                                  review  sentiment
23348  a guy  with the unlikely name of shy walker  l...          0
16753  this is perhaps the worst movie i have ever se...          0
6040   i came across this movie back in the mid eight...          1
24586  most movies i can sit through easily  even if ...          0
16135   iphigenia  is the great achievement of michae...          1
...                                                  ...        ...
22274  this movie is certainly one of the greatest fi...          1
27203  never having read or seen the bard s original ...          1
49815  i was never all that impressed by night galler...          1
23933  i d never heard of this aussie horror prior to...          1
34531  this is one of the periphery stories told by t...          1

[10000 rows x 2 columns]

In [24]:
#defining a function to remove stopwords from text
def remove_stopwords(text):
    x = []
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)
    y = x[:]
    x.clear()
    return y

In [25]:
# applying the remove_stopwords function to the 'review' column
df['review'] = df['review'].apply(remove_stopwords)

In [26]:
df

                                                  review  sentiment
23348  [guy, unlikely, name, shy, walker, looks, two,...          0
16753  [perhaps, worst, movie, ever, seen, seen, well...          0
6040   [came, across, movie, back, mid, eighties, tee...          1
24586  [movies, sit, easily, even, particularly, like...          0
16135  [iphigenia, great, achievement, michael, cacoy...          1
...                                                  ...        ...
22274  [movie, certainly, one, greatest, films, ever,...          1
27203  [never, read, seen, bard, original, work, begi...          1
49815  [never, impressed, night, gallery, one, episod...          1
23933  [never, heard, aussie, horror, prior, michael,...          1
34531  [one, periphery, stories, told, animatrix, dir...          1

[10000 rows x 2 columns]

In [27]:
#  import PorterStemmer from NLTK for word stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [28]:
# defining a function to perform stemming on a list of words
y = []
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z = y[:]
    y.clear()
    return z

In [29]:
# testing the stem_words function with a sample list of words
stem_words(['I', 'loved', 'loving', 'it'])

['i', 'love', 'love', 'it']

In [30]:
# applying the stem_words function to the 'review' column
df['review'] = df['review'].apply(stem_words)

In [31]:
df

                                                  review  sentiment
23348  [guy, unlik, name, shi, walker, look, two, dau...          0
16753  [perhap, worst, movi, ever, seen, seen, well, ...          0
6040   [came, across, movi, back, mid, eighti, teenag...          1
24586  [movi, sit, easili, even, particularli, like, ...          0
16135  [iphigenia, great, achiev, michael, cacoyanni,...          1
...                                                  ...        ...
22274  [movi, certainli, one, greatest, film, ever, m...          1
27203  [never, read, seen, bard, origin, work, begin,...          1
49815  [never, impress, night, galleri, one, episod, ...          1
23933  [never, heard, aussi, horror, prior, michael, ...          1
34531  [one, peripheri, stori, told, animatrix, direc...          1

[10000 rows x 2 columns]

In [32]:
# defining a function to join a list of words back into a string
def join_back(list_input):
    return " ".join(list_input)

In [33]:
# applying the join_back function to the 'review' column
df['review'] = df['review'].apply(join_back)

In [34]:
df['review']

23348    guy unlik name shi walker look two daughter co...
16753    perhap worst movi ever seen seen well 300 movi...
6040     came across movi back mid eighti teenag immedi...
24586    movi sit easili even particularli like movi ty...
16135    iphigenia great achiev michael cacoyanni maste...
                               ...
22274    movi certainli one greatest film ever made sto...
27203    never read seen bard origin work begin compar ...
49815    never impress night galleri one episod stand t...
23933    never heard aussi horror prior michael elliott...
34531    one peripheri stori told animatrix directli re...
Name: review, Length: 10000, dtype: object

In [35]:
#  extract the 'review' column as a feature matrix X
X = df.iloc[:, 0:1].values

In [36]:
# displaying the shape of the feature matrix X
X.shape

(10000, 1)

In [37]:
#  import CountVectorizer for text feature extraction
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000)

In [38]:
X = cv.fit_transform(df['review']).toarray()

In [39]:
X.shape

(10000, 1000)

In [40]:
X[0].mean()

0.164

In [41]:
#extract the target variable y from the 'sentiment' column
y = df.iloc[:, -1].values

In [42]:
y.shape

(10000,)

 - X,y
 - Training set
 - Test Set(Already know the result)

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [45]:
X_train.shape

(8000, 1000)

In [46]:
X_test.shape

(2000, 1000)

In [47]:
y_train.shape

(8000,)

In [48]:
y_test.shape

(2000,)

In [49]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [50]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [51]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)

BernoulliNB()

In [52]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)
y_pred3 = clf3.predict(X_test)

In [53]:
y_test.shape

(2000,)

In [54]:
y_pred1.shape

(2000,)

In [55]:
from sklearn.metrics import accuracy_score

In [56]:
print("Gaussian", accuracy_score(y_test, y_pred1))
print("Multinomial", accuracy_score(y_test, y_pred2))
print("Bernaulli", accuracy_score(y_test, y_pred3))

Gaussian 0.7915
Multinomial 0.8305
Bernaulli 0.827